import { StockDefinition } from "../types/stock";

export const STOCKS: StockDefinition[] = [
  {
    currency: "USD",
    yahooSymbol: "ZLAB",
    name: "再鼎医药（ZLAB.US）",
    futunnParam: "ZLAB-US",
    aastocksCode: "ZLAB",
  },
  {
    currency: "USD",
    yahooSymbol: "PDD",
    name: "拼多多（PDD.US）",
    futunnParam: "PDD-US",
    aastocksCode: "PDD",
  },
  {
    currency: "USD",
    yahooSymbol: "SVA",
    name: "科兴生物（SVA.US）",
    futunnParam: "SVA-US",
    aastocksCode: "SVA",
  },
  {
    currency: "HKD",
    yahooSymbol: "2142.HK",
    name: "和铂医药（2142.HK）",
    futunnParam: "02142-HK",
    aastocksCode: "02142",
  },
  {
    currency: "HKD",
    yahooSymbol: "9966.HK",
    name: "康宁杰瑞（9966.HK）",
    futunnParam: "09966-HK",
    aastocksCode: "09966",
  },
  {
    currency: "HKD",
    yahooSymbol: "1875.HK",
    name: "东曜药业（1875.HK）",
    futunnParam: "01875-HK",
    aastocksCode: "01875",
  },
  {
    currency: "RMB",
    yahooSymbol: "688382.SS",
    name: "益方生物（688382.SH）",
    futunnParam: "688382-SH",
    aastocksCode: "688382",
  },
  {
    currency: "USD",
    yahooSymbol: "CNTB",
    name: "康乃德（CNTB.US）",
    futunnParam: "CNTB-US",
    aastocksCode: "CNTB",
  },
  {
    currency: "USD",
    yahooSymbol: "ZH",
    name: "知乎（ZH.US）",
    futunnParam: "ZH-US",
    aastocksCode: "ZH",
  },
  {
    currency: "HKD",
    yahooSymbol: "1244.HK",
    name: "3D MEDICINES（思路迪）",
    futunnParam: "01244-HK",
    aastocksCode: "01244",
  },
  {
    currency: "HKD",
    yahooSymbol: "6955.HK",
    name: "博安生物（6955.HK）",
    futunnParam: "06955-HK",
    aastocksCode: "06955",
  },
  {
    currency: "USD",
    yahooSymbol: "YMM",
    name: "满帮（YMM.US）",
    futunnParam: "YMM-US",
    aastocksCode: "YMM",
  },
  {
    currency: "RMB",
    yahooSymbol: "301216.SZ",
    name: "万凯新材（301216.SZ）",
    futunnParam: "301216-SZ",
    aastocksCode: "301216",
  },
  {
    currency: "HKD",
    yahooSymbol: "9886.HK",
    name: "叮当健康（9886.HK）",
    futunnParam: "09886-HK",
    aastocksCode: "09886",
  },
  {
    currency: "HKD",
    yahooSymbol: "2888.HK",
    name: "Standard Chartered Bank（2888.HK）",
    futunnParam: "02888-HK",
    aastocksCode: "02888",
  },
  {
    currency: "HKD",
    yahooSymbol: "0005.HK",
    name: "HSBC（0005.HK）",
    futunnParam: "00005-HK",
    aastocksCode: "00005",
  },
  {
    currency: "HKD",
    yahooSymbol: "3968.HK",
    name: "CMB（3968.HK）",
    futunnParam: "03968-HK",
    aastocksCode: "03968",
  },
  {
    currency: "USD",
    yahooSymbol: "EWBC",
    name: "East West Bank（EWBC）",
    futunnParam: "EWBC-US",
    aastocksCode: "EWBC",
  },
  {
    currency: "USD",
    yahooSymbol: "JPM",
    name: "JP Morgan（JPM）",
    futunnParam: "JPM-US",
    aastocksCode: "JPM",
  },
  {
    currency: "USD",
    yahooSymbol: "MS",
    name: "Morgan Stanley（MS）",
    futunnParam: "MS-US",
    aastocksCode: "MS",
  },
  {
    currency: "USD",
    yahooSymbol: "GS",
    name: "Goldman Sachs（GS）",
    futunnParam: "GS-US",
    aastocksCode: "GS",
  },
  {
    currency: "USD",
    yahooSymbol: "FCNCA",
    name: "First Citizens（FCNCA）",
    futunnParam: "FCNCA-US",
    aastocksCode: "FCNCA",
  },
  {
    currency: "USD",
    yahooSymbol: "UBS",
    name: "UBS（UBS）",
    futunnParam: "UBS-US",
    aastocksCode: "UBS",
  },
  {
    currency: "USD",
    yahooSymbol: "C",
    name: "Citibank（C）",
    futunnParam: "C-US",
    aastocksCode: "C",
  },
  {
    currency: "HKD",
    yahooSymbol: "2590.HK",
    name: "极智嘉（2590.HK）",
    futunnParam: "02590-HK",
    aastocksCode: "02590",
  },
  {
    currency: "HKD",
    yahooSymbol: "1511.HK",
    name: "驭势科技（1511.HK）",
    futunnParam: "01511-HK",
    aastocksCode: "01511",
  },
  {
    currency: "USD",
    yahooSymbol: "TME",
    name: "TME.US",
    futunnParam: "TME-US",
    aastocksCode: "TME",
  },
  {
    currency: "HKD",
    yahooSymbol: "3952.HK",
    name: "来福谐波（3952.HK）",
    futunnParam: "03952-HK",
    aastocksCode: "03952",
  },
  {
    currency: "HKD",
    yahooSymbol: "6880.HK",
    name: "MOMENTA-W（6880.HK）",
    futunnParam: "06880",
    aastocksCode: "06880",
  },
];
